### ISSUE TITLE
Rename UncompressedChange

### ISSUE THREAD

**Issue by jeffa5** [automerge/automerge-rs#114]
Since changes can now actually be compressed (after processing in the backend) the name for the change that a frontend generates seems a bit off:
https://github.com/automerge/automerge-rs/blob/3a8447c068f21256904cab53a553e362cb7ebc14/automerge-protocol/src/lib.rs#L417

Perhaps we should rename that to be the canonical `Change` since it holds all change information nicely in the struct and move the existing `Change` to `BinaryChange` or `EncodedChange`?

**Comment by alexjg** [comment]
I like `EncodedChange` personally. However, I think @orionz likes the current naming because within the backend codebases changes are always an  encoded change. I suspect the correct solution is actually to call both things a `Change` and use import aliases within the backend codebase when referring to an `automerge_protocol::Change` (currently `UncompressedChange`).
