### ISSUE TITLE
quickcheck-based testing

### ISSUE THREAD

**Issue by spacejam** [automerge/automerge-rs#15]
Hello :)

I'm excited to see automerge coming to the Rust ecosystem!

One of the most effective time-saving engineering techniques I used while writing the first version of https://github.com/rust-crdt/rust-crdt (and most of my projects since then) was to use quickcheck to generate randomized operations, then permute that sequence of operations, then assert that all permutations of applications converged to an identical final state after all operations were applied. You can also clone them to assert idempotency. This is orders of magnitude more effective than most example/table-driven testing. Personally, I hate writing tests, but I take a huge amount of satisfaction when the machine spits back a failing example that illuminates a bias I encoded in the system. 

The really nice thing is that quickcheck will then shrink the failing set of operations down to the minimum set that still causes the bug to jump out, effectively telling a story for you to more easily debug what happened compared to staring at a chain of 1000 random operations and not knowing what could have gone wrong. It basically is a way to write like 50 lines of test code that then generates millions of interesting tests that keep mining for bugs in your implementation, avoiding the "pesticide paradox" where your code just becomes immune to your static tests.

I initially just cloned this repo to implement something similar, but I realized that some of the functionality is a bit scattered across various sub-crates, which adds friction to testing.

I see that `Backend` is doing a bit of the merging work, scattering the logic of the CRDT across the protocol and backend subcrates. The reason why this adds friction is because it is quite convenient to conditionally derive the `Arbitrary` trait which allows random instances of a type to be synthesized during testing, but if you want to do this for multiple crates in a way that is only done at testing-time, you have to start adding compile-time features (the `#[cfg(test])` attribute is not transitive to dependencies during testing). 

So, there are 2 options to still accomplish this, if you are interested:
1. introduce a testing conditional compilation feature that then triggers the `Arbitrary` trait to be derived for various types (relatively unintrusive)
2. merge backend and protocol, or at least push the least upper bound function for the automerge CRDT into protocol (much more intrusive, but maybe in useful ways?)

would you be interested in either of these, to facilitate making automerge-rs far more reliable through the use of generative testing?

**Comment by spacejam** [comment]
oh yeah, this also unlocks using hit-tracing fuzzers to find even more bugs in combination with quickcheck https://github.com/rust-fuzz/arbitrary

**Comment by alexjg** [comment]
Hey! Great to have you here, I've been following rust-crdt for a while, I really like what you've done there.

Vis a vis model based tests. I've had a crack at building them for automerge before, in the javascript implementation [here](https://github.com/alexjg/automerge/blob/model-based-testing/test/model_test.ts). I ran into two problems:

1. I found it very difficult to generate a useful `Arbitrary` instance for automerge operations directly. The problem is that an operation is not valid in it's own right, it depends on previous operations. For example, an operation setting the key of an object to some value needs to know the operation ID of the operation which created the parent object. I ended up instead working in a language of operations on paths into the state of the CRDT. This worked but it was quite awkward
2. Even once I had gotten the above test working, I couldn't get it to explore any interesting parts of the state space. Partly this was to do with performance being a problem, which meant that I couldn't generate a lot of examples, but it's also that the interesting parts of the algorithm are quite unlikely to occur in entirely random mutations. I ended up in situations where my unit tests were surfacing bugs (usually to do with many concurrent list insertions) which I couldn't get the model based test to reproduce.

Now, I am in general very enthusiastic about model based testing and it seems a shame to me that a project with such an obvious property to test as a CRDT doesn't have a model based test so I would be very interested in any experience you have with model based testing that you can bring to bear. On that basis, let's explore what changes we might make to make model based testing possible.

To your point about logic being scattered across several crates. I assume that you're referring to the backend/frontend split? Could you explain to me how that is a problem for property based tests? The main property I had been thinking of testing was something along the lines of "if two instances of the CRDT have applied the same set of operations, then they have the same state". The backend contains the entire state of the CRDT so it should be possible to apply operations to two different instances of the backend in arbitrary orders and then assert that they have the same state right?

There are additional properties that we would want to test to do with the way that the frontend and backend communicate, for example "the backend always emits patches to the frontend in the order that change requests were received from the frontend".

I guess to my mind the biggest problem I have with model based testing here is that I can't figure out how to generate an interesting, arbitrary set of operations. But yeah, would welcome your thoughts on all of the above.
