### ISSUE TITLE
FFI interface and reuse from higher level languages. Design question.

### ISSUE THREAD

**Issue by winwisely99** [automerge/automerge-rs#16]
I would like to use this from not just just but other languages.

Our project currently uses OT, and not CRDT.
SO we are stuck with a central server in order to maintain ordering.

But we now are going P2P with no central server and so using CRDT.

The clients are Dart and the backend SAAS layer are anything, but tend to be golang.
So in this multi lang world, i was wondering if Protobuf would be a possibility ?

Protobufs can "embed" other protobufs these days by using the Any first class type also.
Which is useful when you want a primary data plane using protobufs, that can carry other people Protobufs. 

I know this is really an Issue talking about Architecture, and i a proposing a possible solution to the reuse problem.

Rust is a really good choice and so is WASM. Others are also embracing it.
https://github.com/envoyproxy/envoy-wasm
- So you can build massive systems where the dataplane itself can do CRDT for example.
- We use this currently for various things we need to do like Privacy protection

**Comment by alexjg** [comment]
Hey! Glad to have you here. We are definitely interested in FFI, @orionz has been working on such a thing, you can see the current state of that in the `automerge-c` crate in this repo. It's very experimental and likely to change dramatically (like everything in this repo at the moment) but take a look, we would love your feedback on it as supporting good FFI is part of the reason for this project.

To your point about protobuf. In general I would not expect protobuf to be a good format for automerge. A naive encoding of operations tends to lead to increase in storage of several orders of magnitude, as well as performance problems when loading documents. Fixing this is the primary objective of the `performance` branch of the javascript implementation and it revolves around a custom encoding of changes. However, we're working hard to design this library so that the application should never need to actually examine the changes in this format, the library accepts a `Vec<u8>` and handles decoding those changes itself, so you should only need to ship bytes around. Does that fit with your usecase?
