### ISSUE TITLE
access control probably needs some support in the crdt

### ISSUE THREAD

**Issue by dvc94ch** [automerge/automerge-rs#223]
For example, how do you change your profile picture and who can change your profile picture. Currently if you have something like this:
```
{ "cards": [], "users": { "pubkey": "profile picture" } }
```
anyone could change someone elses profile picture.

**Comment by alexjg** [comment]
This is an interesting problem. I've been thinking about this in the context of radicle.xyz, where we're using Automerge to implement metadata about software projects such as issues or kanban boards (RFC [here](https://github.com/radicle-dev/radicle-link/pull/662)). In this context we will want to do things like only allow someone who created a comment on an issue to modify it. For the first iteration we're doing a simple thing which is only allowing project maintainers to modify collaborative objects. That means that for each Automerge document we have a set of keys which are allowed to modify that document and we only accept changes which are signed by one of those keys.

In general though we want to be able to do more complex things. My current thinking is that for each document you also ship an access control policy defined using something like [SecPAL](https://content.iospress.com/articles/journal-of-computer-security/jcs364). These policies are defined using Datalog with constraints and might look a bit like this:

```
creator says x can insert y 
if 
    x isAuthor y
where
    y < comments
```

This is a made up logic, but `<` is a "direct child" predicate, "x isAuthor y" is true if the object at `y` was created by the princiapl `x` and `insert y` is an action matching one of the operations in the Automerge operation model.

There's more details on this approach in the SecPAL paper but it feels flexible enough to describe a lot of different access control problems and queries on it run in time polynomial in the size of the access control policy (this is important because I think you would need to run the query for every automerge operation).

To make all of this useful you'll need some concept of identity. For Radicle we have a PKI provided by the rest of the Radicle network which we can use. I don't think automerge should be opinionated about this, you should be able to use whatever identity system you want. All of this machinery is on top of Automerge, all Automerge needs to provide which it doesn't currently is a way to filter operations as the document is loading.

Anyway, these are some very raw thoughts I have had on this, once I've got the first version of Radicle's collaborative objects built I'll be turning my attention to access control and will hopefully be able to flesh this out more.

**Comment by orionz** [comment]
The auth portion of CRDT's is currently out of scope for automerge.   Don't merge changes from actors you don't trust.   Reject changes that make un-sound edits to a document.  As I have yet to see a really good mixed trust multi user abstraction emerge for CRDT's I am hopeful that we'll see some automerge wrappers emerge that layer on these features.

**Comment by shishkin** [comment]
I think users can do a lot themselves without automerge building authn and authz into the library. All that is needed is some hook that will allow the user to check each incoming change against the current version of the document and potentially reject it. Simple policy can be embedded into the document itself, so that policy can also control who can change the policy.

**Comment by shishkin** [comment]
As for the use case for a mixed trust p2p environment, consider one user owning several devices, connected into a p2p network (like syncthing). CRDTs can help model the shared config of the mesh. If one device gets stolen, it should be removed from the mesh by one of the peers and, if done promptly, other peers should stop accepting updates from the compromised peer.

In a more open scenario of a p2p network, you can't really control other peer's software, so you have to account for malicious clients. So if you would share a folder in syncthing with someone else, you would be glad if syncthing enforced permissions. Not that it's impossible to do without CRDTs, but CRDTs are great for exactly this kind of things and can improve UX of existing solutions.

**Comment by retrohacker** [comment]
@shishkin we are doing something similar

to enforce auth, we extract the ExpandedChanges into a separate block forest that is gossipable. As nodes ingress those blocks they validate the auth at the block level before applying the changes to the crdt.

this (currently) limits us to document level auth, will explore applying auth to objects/paths in the future.

**Comment by alexjg** [comment]
Don't worry, it's coming 🙂. If you join the DIscord you see we have an upcoming community event where we'll talk a lot about the Beehive project.

**Comment by shishkin** [comment]
> Don't worry, it's coming 🙂. If you join the DIscord ...

Good to hear, I really look forward to it. I hate Discord's UX so will gladly miss that. If you have any RSS-based update channel, please share it (I'm already subscribed to InkAndSwitch notebooks).

**Comment by alexjg** [comment]
Well, the event is in Discord, i.e. it's a video call in the Automerge discord. We will do our best to record it for people to watch later.

**Comment by OlivierLDff** [comment]
Hi, how to join the discord to access the talk? The invite link seems to be expired in the readme

**Comment by retrohacker** [comment]
This link worked for me: https://discord.gg/HrpnPAU5zx
