### ISSUE TITLE
Upgraded automerge-rs and my old data does work anymore

### ISSUE THREAD

**Issue by lightsprint09** [automerge/automerge-rs#243]
I upgraded from 14d92e513c1d7f9a66cdce7b6894b5bb17df32d6 to cf2a5125a198653b83490b2c996e4f6982f98e57 and now my data does not work anymore. I thought the data format is stable now.
I attached my binary here [automerge-binary.txt](https://github.com/automerge/automerge-rs/files/7560714/automerge-binary.txt)

**Comment by alexjg** [comment]
I can't seem to get that to load with 14d92e5. I also can't get it to load with the javascript implementation. Any chance you've attached the wrong file?

**Comment by lightsprint09** [comment]
Did you copy the byte-Array content from within the txt file to create a document or just load the file?

**Comment by alexjg** [comment]
I just assumed it was a binary automerge file that happened to be named `.txt` :slightly_smiling_face: . Can you post a raw binary to avoid any ambiguity.

**Comment by lightsprint09** [comment]
Ok, Here is a file directly from disk containing all change. I just renamed the suffix to txt.
[Places.txt](https://github.com/automerge/automerge-rs/files/7562744/Places.txt)

**Comment by alexjg** [comment]
What's the error you're getting when loading?

**Comment by lightsprint09** [comment]
I don't get any error because I use the C API.

**Comment by alexjg** [comment]
I think what you are running into is a result of the fix for #240. This is a backwards incompatible change and any documents generated with the old version of automerge will not decode with either the fixed version or the javascript version. Fixing old documents is going to be tough if you're using the C backend. If you're using the automerge backend you could use the `load_document_without_hash_verification` to load the old document and then `save` to save it as a new document in the correct format.

**Comment by lightsprint09** [comment]
Ok. Thanks for clarification.
