### ISSUE TITLE
Release automerge (Rust) to crates.io

### ISSUE THREAD

**Issue by jeffa5** [automerge/automerge-rs#405]
The Rust implementation of Automerge is pretty mature now, with it working with the js suite of tests, having a wasm and js frontend on top of it and it seeing some adoption. Therefore I think it is about time that we cut an initial release to crates.io.

This would enable more uptake as it at least has some semblance of stability and we can keep better track of when things change (rather than having people pin the git and have to bisect things if an update breaks things).

Having it released further helps stabilisation and releases of related projects as they can pin a version rather than use the git versions again.

It is currently set to use version `0.1.0` which I think is reasonable.

Currently we have two crates for automerge on `crates.io`: 
- https://crates.io/crates/automerge
- https://crates.io/crates/automerge-rs
both owned by @alexjg, perhaps you could add some of us as owners of the crate so we can release too? (https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner). In future we can work to have this released from github actions on a tag/release in github but let that not delay us now.

I'd think we want to go with automerge, since crates.io is for Rust crates and not js or wasm things anyway.

### Changelog

I think that after this release we should also start keeping a changelog file (e.g. https://keepachangelog.com/en/1.0.0/) so that everyone can inspect what changes in new releases and can update code accordingly!

### Current blockers

This section lists any outstanding issues or PRs that MUST be fixed / merged before the initial release, I don't think heavy performance work is necessary in this, mainly large bug fixes, of which I'm not aware of many.

- https://github.com/automerge/automerge-rs/issues/394

cc: @ept @orionz @alexjg

**Comment by alexjg** [comment]
I'm inclined to agree with this. I'll sort out crates.io stuff tomorrow. One thing I think we should do - apropos of the changelog - is to start being much stricter about commit discipline, having discrete commits with good commit messages makes generating a changelog easy

**Comment by jeffa5** [comment]
Great! For the commits, did you have a particular scheme in mind to help? https://www.conventionalcommits.org/en/v1.0.0/ perhaps?

**Comment by alexjg** [comment]
I personally don't find conventional commits particularly useful at a project of this size. I think it's more just a case of including the commit messages in code review. I'm not against conventional commits if others would like that approach though.

**Comment by tombh** [comment]
As someone new to (and very excited about) this project, perhaps my fresh eyes can offer a bit of perspective. It seems to me that the out of date README is the more pressing issue. The repo URL itself has "rs" in it and the README states that of all the language versions, the Rust version is "the most mature". There's also the mention of the "frontend/backend split", which is no longer the case.

Only from talking to @alexjg on Slack did it become clear that the Rust version is really actually just the underlying library abstraction. So whilst I certainly understand the sense of the Rust version being the most mature, I think that's misleading because it's comparing apples to oranges. As in, the Rust version has a fundamentally different remit. When reading the [docs](https://automerge.org/docs/hello/) (which are great BTW) it's clear that JS is being made front and centre, which makes sense as that's very likely the way Automerge is going to be most useful and find the most adoption.

I think the delay in releasing the Rust crates reflects this alternative nature to the Rust version? Of course we hope, and there's certainly no reason why it couldn't happen, that the Rust version starts to take a similar role to the others, but for now I think the priority is simply plainer communication.

I could make a PR with my suggested changes to the README if that would help kick off a conversation?

**Comment by alexjg** [comment]
Definitely I would be interested in seeing the README updates you're talking about, go ahead and hit that PR :slightly_smiling_face: 

However, I think we should also release a rust crate. @orionz @jeffa5 do you think there's any reason to hold off on this any longer?

**Comment by tombh** [comment]
Thanks @alexjg 🙂 Done: https://github.com/automerge/automerge-rs/pull/417

**Comment by jeffa5** [comment]
@alexjg Nothing blocking it from me

**Comment by alexjg** [comment]
@orionz has pushed this to crates.io: https://crates.io/crates/automerge

@orionz can you push the version increase to `main` and then we can close this issue.

**Comment by anlumo** [comment]
The readme is broken on crates.io for some reason…
