### ISSUE TITLE
Object.freeze doesn't work on doc

### ISSUE THREAD

**Issue by fo-fo** [automerge/automerge-rs#432]
I noticed the following issue while trying to take automerge-wasm/automerge-js into use: `Object.freeze` doesn't work on the proxified doc.

Here's a repro (in Node v16.13.1),

```
const Automerge = require("automerge-js");
const wasm_api = require("automerge-wasm");

Automerge.use(wasm_api);
const doc = Automerge.init();
Object.freeze(doc);
```

and the error is:
```
index.js:6
Object.freeze(doc);
       ^

TypeError: 'ownKeys' on proxy: trap result did not include 'context'
    at Function.freeze (<anonymous>)
    at Object.<anonymous> (index.js:6:8)
```

Longer story: I'm using Redux Toolkit, which uses Immer, which tries to do a deep Object.freeze() (by default) on the entire Redux state. I have a combination of normal JS objects and Automerge docs in the Redux state, so that's how I ran into this problem.

**Comment by orionz** [comment]
The version you are using uses a proxy object for the document so it cannot be frozen.  The newer version (in alpha) is being published as the package `@automerge/automerge` comes with a bunch of differences.  First it does not require manually attaching the wasm backend as it is now integrated.  Second the document is a normal javascript object updated incrementally instead of a proxy and will be able to be used directly in something Redux as `===` will now work.  The `Automerge.init({ freeze: true })` currently only freezes the top level object but I just opened a PR to properly carry it down to all the sub objects.  I expect this to be merged Monday and a new package to be published then. 

https://github.com/automerge/automerge-rs/pull/444

If you try this package please let us know how it goes for you. =)
