### ISSUE TITLE
Common API between Automerge and Transaction

### ISSUE THREAD

**Issue by bluebear94** [automerge/automerge-rs#443]
It should be possible to issue read-only operations such as `get` generically over both `&Automerge` and `&Transaction` so that functions that want to call only these operations can work on both of these types.

**Comment by orionz** [comment]
Have you looked at `AutoCommit` - it wraps `Automerge` and `Transaction` into a single object and managed opening and closing transactions for you.

**Comment by bluebear94** [comment]
This isn’t always appropriate:

* sometimes you always want to start transactions explicitly, and
* sometimes you want to share an Automerge document across multiple threads (with something like `Arc<RwLock<...>>`, and you don’t want one thread to unexpectedly split a sequence of operations in another thread that were intended to be in a single transaction.

**Comment by teohhanhui** [comment]
I have the exact same problems with @bluebear94.

There needs to be a variant of `AutoCommit` where sync waits on a transaction to complete, and vice versa. Not force a commit and cause changes to become interleaved, which defeats the purpose of having a transaction in the first place. Imagine handler code which is halfway through making some changes to the document, and sync daemon running on another thread.

**Comment by alexjg** [comment]
I'm planning on reviewing the Rust API soon and seeing if we can factor things a bit more cleanly. It does seem like "get" operations should be generic over `Automerge`, `AutoCommit`, and `Transaction`. But maybe the behaviour of when to commit transactions should be parameterised dfifferently anyway.

To that last point, I'm curious about the reasons you folks want to control when transactions are created. I can think of usecases but @teohhanhui @bluebear94 it would be great if you could describe what you're trying to achieve with explicit control over transactions, it would help with the API design.

**Comment by teohhanhui** [comment]
I imagine something like a `CommitGuard` (`TransactionGuard`?) might work:

```rust
{
    let _tx_guard = doc.new_transaction(); // `begin_transaction`?
    let id = doc.put_object(
        automerge::ROOT,
        Prop::Map("authors".to_owned()),
        ObjType::Table,
    )?;
    // ...
} // commit when _tx_guard dropped
```

**Comment by teohhanhui** [comment]
> To that last point, I'm curious about the reasons you folks want to control when transactions are created. I can think of usecases but @teohhanhui @bluebear94 it would be great if you could describe what you're trying to achieve with explicit control over transactions, it would help with the API design.

Just CRUD stuff in `axum` handlers (through an ORM layer, let's say an `EntityManager`), and a sync daemon running on a different thread.

The `AutoCommit` is shared as `Arc<RwLock<AutoCommit>>` between the `EntityManager` and the sync daemon.

In the handlers, we'd do CRUD on entities which are mapped into the automerge document. We'd like the ability to make sure a set of changes (from the POV of an `axum` handler) is atomic, hence the need for a transaction.

The way that `AutoCommit` is currently designed, when our sync daemon receives a set of changes, thus calling `AutoCommit::receive_sync_message`, if an `axum` handler is halfway through making changes to some entities, the dirty state would get committed immediately (because of `AutoCommit::ensure_transaction_closed`), thus breaking up the set of changes.

We could hold on to the `RwLockWriteGuard` in our `EntityManager`, but that would practically mean database-level locking, which is really not great when something is waiting on I/O in any of the `axum` handlers...

**Comment by alexjg** [comment]
Thanks for the detailed description. I will come back to this in more detail tomorrow but here are some things which occur to me. Currently `Automerge` is not designed to be mutated from multiple threads, the model is instead that you would have an `Automerge` on each thread and ship changes between threads. That's fine for local first applications but on the server side this might be a concern for memory usage (and also actor ID growth). This seems to point towards having some kind of shared storage between threads, which I'll try and write something up about.

If we had some sort of shared storage so that you can have an `Automerge` on each thread then maybe we wouldn't need the transaction abstraction at all (i.e. `Autocommit` might be all we need), if you want to discard some changes you just don't merge your changes back into whichever thread you're syncing from.

**Comment by teohhanhui** [comment]
Hmm... If sync is handled for us then we'd of course be happy to just use the wrapper :stuck_out_tongue_closed_eyes:

The very existence of our sync daemon is due to that not being handled...

**Comment by bluebear94** [comment]
Should have said this earlier, but my original motivation for this was for updating [automergeable](https://github.com/jeffa5/automergeable) to use the latest Automerge API, in which the data of compound values aren’t stored in `Value`. As a result, deserializing these values would require access to the document itself. I wanted these functions to be called both when you have access to the document itself and when you have a transaction to it.

**Comment by alexjg** [comment]
Just a note that this is still on my radar. Right now I'm working on simulating various sync scenarios so that we can measure the impact of the various problems that we would like to solve here. I will come back to this issue once I've got some data from that experiment.

**Comment by alexjg** [comment]
In `automerge-0.3.0` we introduced `ReadDoc` (https://docs.rs/automerge/0.3.0/automerge/trait.ReadDoc.html) and `SyncDoc` (https://docs.rs/automerge/0.3.0/automerge/sync/trait.SyncDoc.html) which I think solves this issue.
