### ISSUE TITLE
Strategy for Stateless Server Synchronization

### ISSUE THREAD

**Issue by anlumo** [automerge/automerge-rs#461]
Based on [the documentation](https://automerge.org/docs/how-it-works/backend/), if I want to implement a server as a centralized data store with a database backend, I have to do the following things when there's a client-side change:

* Load document using `Automerge.load()`.
* Apply changes using `Automerge.applyChanges()`.
* Save to the database using `Automerge.save()`.

If I have a WebSocket, in theory I could keep the document in memory as long as the connection is open to avoid the frequent (and probably expensive) serialization/deserialization steps.

However, if I want to use a stateless system like the [Amazon API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api.html) where WebSocket messages are transformed into HTTP requests internally (with the generic gateway keeping the TCP socket alive), this is not possible.

So, is there a way to simply add changes to the database without having to go the roundtrip through an Automerge document? For the initial synchronization step after a client gets online it's clear that I need the whole document, but if they constantly send small changes through the WebSocket, that might get inefficient really quickly.

**Comment by alexjg** [comment]
`Automerge.save` saves the entire history of the document. However, you can also save a smaller number of changes in the document using `Automerge.getChanges`. One way you could use this would be instead of having the client send the entire document to the backend you could just send the new changes. The API gateway would then ship these changes off to something which appends them to a log. Then a separate process can periodically compact the change log. When fetching the document the API gateway would return the compacted document plus any changes in the change log.

The code on the client then would look something like this:

```javascript
let doc = ... // somehow get the document
const oldHeads = automerge.getHeads(doc)

doc = automerge.change(doc, doc => {
    // make your changes
})

let changes = automerge.getChanges(automerge.view(doc, oldHeads), doc)

network.sendChanges(changes) // send your changes to the api gateway
```

**Comment by anlumo** [comment]
Does that compacting step do more than just appending changes to a list? Otherwise I could just keep the changes separately in the database and fetch all of them when I need the document.

**Comment by alexjg** [comment]
The compact document format uses significantly less space than the individual change format because it uses a bunch of tricks (some of them outlined [here](https://github.com/automerge/automerge-perf/blob/master/columnar/README.md), and specified [here](https://alexjg.github.io/automerge-storage-docs/)) to compress the CRDT metadata. How significant this is for your usecase depends on what kind of data you're working with and how fast moving you expect it to be. For collaborative text in particular you will almost certainly want to compact.

**Comment by anlumo** [comment]
Ok, thank you for the ideas!
