### ISSUE TITLE
Uncaught exception when applying a client-side change

### ISSUE THREAD

**Issue by cklokmose** [automerge/automerge-rs#469]
When applying a change from another client that has been relayed over a node.js server through a web socket, I get an Uncaught exception from auto merge_wasm_bg.js:1102.

Here's a small node.js project that replicates the error.
```
npm install
./node_modules/webpack/bin/webpack.js
node.js index.js
```

Now open two browser tabs to localhost:8888, open the console, and click the 'Do Change' button.

[automerge-bug.zip](https://github.com/automerge/automerge-rs/files/10132384/automerge-bug.zip)

**Comment by alexjg** [comment]
Alright, so the basic problem here is the following code:

```
socket.addEventListener('message', (msg) => {
	let change = msg.data;
	let patch;
	let newDoc;
	[newDoc, patch] = Automerge.applyChanges(amDoc, [change]);		
});
```

The type of `change` here is `ArrayBuffer`. However, `applyChanges` expects an `Array<Uint8Array>` as it's second argument. So to make this work you do:

```
socket.addEventListener('message', (msg) => {
	let change = new Uint8Array(msg.data);
	let patch;
	let newDoc;
	[newDoc, patch] = Automerge.applyChanges(amDoc, [change]);		
});
```

The real problem here though is that we produce a completely useless "Uncaught ..." error message, rather than something which actually allows you to figure out what is going on. I'll try and fix that.
