### ISSUE TITLE
Unwrapping None in group_doc_ops

### ISSUE THREAD

**Issue by jeffa5** [automerge/automerge-rs#55]
I'm seeing the following error when trying to use automerge-rs in a project:

```
panicked at 'called `Option::unwrap()` on a `None` value', /home/andrew/.cargo/git/checkouts/automerge-rs-4d74710a78567f28/ca5ddff/automerge-backend/src/change.rs:695:22
```
and this is the section:
https://github.com/automerge/automerge-rs/blob/2cc7b60ccb604756bb06fafa38221781e4df2621/automerge-backend/src/change.rs#L688-L698

I'm not sure what should be done if the value is None at this point but I'm happy to contribute if it is something simple to describe, e.g. just skip it.

**Comment by alexjg** [comment]
Hmm, the issue here is that the predecessor ops of some operation reference a non existent operation. This implies that the operation log is corrupt in some manner. 

What we should do at this particular point is propagate the error through the return type of `group_doc_ops`. This is something I do want to do but I don't think it will solve your problem here because the question is 'how are there missing predecessors'.  Propagating the missing predecessor as an error value will help, but I think we should also add some `tracing` events (at `debug` level) as we load the document to make this stuff more debuggable.
